---
resources:
  - name: m2
    type: docker-image
    source:
      repository: registry-192-168-11-210.sslip.io/making/blog-m2
      username: {{nexus-username}}
      password: {{nexus-password}}  
      email: {{docker-email}}  
  - name: blog-repo
    type: git
    source:
      uri: https://github.com/making/blog-services
      branch: master
  - name: utils
    type: git
    source:
      uri: https://github.com/maki-home/concourse-utils
      branch: master
jobs:
  - name: init-m2
    plan:
      - get: blog-repo
      - get: utils
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: blog-repo
              path: repo
            - name: utils
          outputs:
            - name: to-push  
          run:
            path: sh 
            args: 
            - repo/ci/tasks/m2.sh
            - init
      - put: m2
        params:
          import_file: to-push/rootfs.tar

  - name: update-m2
    plan:
      - get: blog-repo
      - get: utils
      - get: m2
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: blog-repo
              path: repo
            - name: utils
            - name: m2
          outputs:
            - name: to-push    
          run:
            path: sh
            args: 
            - repo/ci/tasks/m2.sh
          params:
            vcap.services.config-service.credentials.uri: {{config-service-url}}
      - put: m2
        params:
          import_file: to-push/rootfs.tar